function get_default_p_value_annotation(curr_p_val, display_style, x_pos, y_pos)
% Part of a set of functions to simplify the making of figures in MATLAB
% (R2024a).
% Code written by Peter Hasenhuetl.

if curr_p_val >= 0.05
    curr_p_val = round(curr_p_val,2);
    if display_style == "p_value"
        annotation('textbox', 'Units','centimeters','Position',[x_pos, y_pos, 1, 0.5], 'string', ...
            'p = ', 'EdgeColor','none',...
            'FontSize',get_default_font_size,'FontWeight','normal','Color','k')
        annotation('textbox', 'Units','centimeters','Position',[x_pos+0.25, y_pos, 1, 0.5], 'string', ...
            string(curr_p_val), 'EdgeColor','none',...
            'FontSize',get_default_font_size,'FontWeight','normal','Color','k')
    elseif display_style == "asterisk"
        annotation('textbox', 'Units','centimeters','Position',[x_pos+0.35, y_pos, 1, 0.5], 'string', ...
            'n.s.', 'EdgeColor','none',...
            'FontSize',get_default_font_size,'FontWeight','normal','Color','k')
    end
       
elseif curr_p_val < 0.05 && curr_p_val >= 0.01
    if display_style == "p_value"
        annotation('textbox', 'Units','centimeters','Position',[x_pos, y_pos, 1, 0.5], 'string', ...
            'p < ', 'EdgeColor','none',...
            'FontSize',get_default_font_size,'FontWeight','normal','Color','k')
        annotation('textbox', 'Units','centimeters','Position',[x_pos+0.25, y_pos, 1, 0.5], 'string', ...
            '0.05', 'EdgeColor','none',...
            'FontSize',get_default_font_size,'FontWeight','normal','Color','k')
    elseif display_style == "asterisk"
        annotation('textbox', 'Units','centimeters','Position',[x_pos+0.35, y_pos, 1, 0.5], 'string', ...
            '*', 'EdgeColor','none',...
            'FontSize',12,'FontWeight','normal','Color','k')
    end
        
elseif curr_p_val < 0.01 && curr_p_val >= 0.001
    if display_style == "p_value"
        annotation('textbox', 'Units','centimeters','Position',[x_pos, y_pos, 1, 0.5], 'string', ...
            'p < ', 'EdgeColor','none',...
            'FontSize',get_default_font_size,'FontWeight','normal','Color','k')

        annotation('textbox', 'Units','centimeters','Position',[x_pos+0.25, y_pos, 1, 0.5], 'string', ...
            '0.01', 'EdgeColor','none',...
            'FontSize',get_default_font_size,'FontWeight','normal','Color','k')
    elseif display_style == "asterisk"
        annotation('textbox', 'Units','centimeters','Position',[x_pos+0.35, y_pos, 1, 0.5], 'string', ...
            '**', 'EdgeColor','none',...
            'FontSize',12,'FontWeight','normal','Color','k')
    end
        
elseif curr_p_val < 0.001
    if display_style == "p_value"
        annotation('textbox', 'Units','centimeters','Position',[x_pos, y_pos, 1, 0.5], 'string', ...
            'p < ', 'EdgeColor','none',...
            'FontSize',get_default_font_size,'FontWeight','normal','Color','k')

        annotation('textbox', 'Units','centimeters','Position',[x_pos+0.25, y_pos, 1, 0.5], 'string', ...
            '0.001', 'EdgeColor','none',...
            'FontSize',get_default_font_size,'FontWeight','normal','Color','k')        
    elseif display_style == "asterisk"
        annotation('textbox', 'Units','centimeters','Position',[x_pos+0.35, y_pos, 1, 0.5], 'string', ...
            '***', 'EdgeColor','none',...
            'FontSize',10,'FontWeight','normal','Color','k')
    end
end




end